version: '3.1'

services:
  db:  # Changed the service name to 'postgres'
    container_name: cardShieldDb  # Explicitly set the container name to 'cardShieldDab'
    image: postgres
    environment:
      POSTGRES_USER: paulDaniel
      POSTGRES_PASSWORD: password
      POSTGRES_DB: cardShield
      PG_DATA: /data/cardShield
    ports:
      - "5333:5432"
    volumes:
      - db:/data/postgres
    networks:
      - db

networks:
  db:
    driver: bridge

volumes:
  db:
