server:
    port: 8080
    error:
        include-message: always

spring:
  main:
      web-application-type: servlet
  datasource:
      url: jdbc:postgresql://localhost:5333/cardShield
      username: paulDaniel
      password: password